### ISSUE TITLE
vuzzer early exit due to exception in function bbdict 

### ISSUE THREAD

**Issue by zjuchenyuan** [vusec/vuzzer64#14]
```
[*] Just about to run  ['BBOUT=/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/d/p/normal/15.ffmpeg', '-y', '-i', '/vuzzer64/fuzzer-code/vutemp/data/avi-textinfo.avi', '-c:v', 'mpeg4', '-c:a', 'copy', '-f', 'mp4', '/dev/null']
[*] Run complete..

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "runfuzzer.py", line 805, in main
    (bbs,retc)=execute(tfl)
  File "runfuzzer.py", line 186, in execute
    bbs = bbdict(config.BBOUT)
  File "runfuzzer.py", line 88, in bbdict
    bbfr=int(tLine[1],0)
IndexError: list index out of range
```

this may be related to issue #13 , where bbc.out is 35GB

**Comment by zjuchenyuan** [comment]
I simply ignore this exception to bypass this issue, can you help me do a better fix?

https://github.com/vusec/vuzzer64/blob/ef51c49dd3e803592aeaa175de554c0405c9218e/fuzzer-code/runfuzzer.py#L805

Change to:

```
                try:
                    (bbs,retc)=execute(tfl)
                except:
                    traceback.print_exc()
                    continue
```

**Comment by tosanjay** [comment]
Hi Chen,
Sorry about not being able to respond. I have just relocated to a different country and trying to settling in. I will get back to it ASAP.
