### ISSUE TITLE
VUzzer64 couldn't generate bbc.out

### ISSUE THREAD

**Issue by MoonLight-SteinsGate** [vusec/vuzzer64#16]
Hi! When I start VUzzer64 to test the base64 from LAVA-M, the runfuzzer.py crashes and notice that the bbc.out is not found.

The version of PIN is 3.7. The initial three seeds is provided by vuzzer32. And all depency has been built as README.md says. The information is showed below:
```
root@moonlight:~/vuzzer64/fuzzer-code# python vuzzer_control.py 5 base64 vuzzer 1 1
fuzz will exec 5.0 hours.
fuzz target base64.
fuzz tool base64.
begin exec python runfuzzer.py -s '/root/target_of_lava/LAVA-M/base64 -d %s' -i '/root/vuzzer64/fuzzer-code/datatemp/b64' -w '/root/vuzzer64/fuzzer-code/idafiles_new/base64.pkl' -n '/root/vuzzer64/fuzzer-code/idafiles_new/base64.names'
[*] Starting dry run now...
[*] Just about to run  ['BBOUT=/root/vuzzer64/fuzzer-code/outd/bbc.out', 'LIBS=#', './run_bb.sh', '/root/target_of_lava/LAVA-M/base64', '-d', '/root/vuzzer64/fuzzer-code/datatemp/b64/f2.b64']
[*] Run complete..

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "runfuzzer.py", line 717, in main
    gbb,bbb=dry_run()
  File "runfuzzer.py", line 545, in dry_run
    (bbs,retc)=execute(tfl)
  File "runfuzzer.py", line 186, in execute
    bbs = bbdict(config.BBOUT)
  File "runfuzzer.py", line 83, in bbdict
    with open(config.BBOUT,"r") as bbFD:
IOError: [Errno 2] No such file or directory: '/root/vuzzer64/fuzzer-code/outd/bbc.out'

init error and end exec
```

**Comment by MoonLight-SteinsGate** [comment]
The reason has been found. It is because the base64 we test is not a 64-bit ELF.
