### ISSUE TITLE
Error when running Vuzzer using example command

### ISSUE THREAD

**Issue by pratikbhd** [vusec/vuzzer64#7]
I have setup Vuzzer on a VirtualBox following all the instructions as mentioned in the README. I tried running runfuzzer.py as mentioned in the wikiHOWTO.md file but received the following error:
'''
$ python runfuzzer.py -s '/home/osboxes/vuzzer/vuzzer64/bin/who %s' -i 'datatemp/utmp/' -w 'idafiles/who.pkl' -n idafiles/who.names -o '0x00000000'

[*] Starting dry run now...
[*] Just about to run  ['BBOUT=/home/osboxes/vuzzer/vuzzer64/fuzzer-code/outd/bbc.out ./run_bb.sh', '/home/osboxes/vuzzer/vuzzer64/bin/who', '/home/osboxes/vuzzer/vuzzer64/fuzzer-code/datatemp/utmp/f1.utmp']
[*] Run complete..

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "runfuzzer.py", line 716, in main
    gbb,bbb=dry_run()
  File "runfuzzer.py", line 545, in dry_run
    (bbs,retc)=execute(tfl)
  File "runfuzzer.py", line 186, in execute
    bbs = bbdict(config.BBOUT)
  File "runfuzzer.py", line 83, in bbdict
    with open(config.BBOUT,"r") as bbFD:
IOError: [Errno 2] No such file or directory: '/home/osboxes/vuzzer/vuzzer64/fuzzer-code/outd/bbc.out'
'''

**Comment by RKX1209** [comment]
Are you using 64bit who binary? I guess you are using who binary from vuzzer repository, which is compiled as 32bit executable.

**Comment by pratikbhd** [comment]
Yes, I was using the who binary provided in the vuzzer repository. I was under the assumption that they too were ported to 64-bit. I will try running them on the 64-bit who library then. Thanks!

**Comment by RKX1209** [comment]
Yeah, It's bit confusing. VUzzers who binary comes from 32bit LAVA-M dataset.
Previously I tried to create 64 bit version of it by using [lava](https://github.com/panda-re/lava), but it doesn't works well.
If you succeed to create 64 bit LAVA-M dataset, it's significant to add these binaries to VUzzer64s repository as bin samples :)

**Comment by cgr71ii** [comment]
Any news on LAVA-M 64-bit binaries? I'm going crazy trying to run these 32-bit binaries with PIN... :(

**Comment by tosanjay** [comment]
Hi @cgr71ii you can download tthe entire LAVA-M dataset from https://sites.google.com/site/steelix2017/home/lava and compile it for 64-bit. it should work well. 
Unfortunately, I am not able to update the LAVA-M binaries yet (sorry about it), but I am about to do a full overhauling of this repo. it will take time though!!

**Comment by cgr71ii** [comment]
That's exactly what I've been trying these days :( Fortunately, I've finally succeeded!

My problem was related to `libacl.so`, since I had no the soft link created, and it is not created in the Ubuntu versions I have tried (16.04, 18.04 and 20.04). After I noticed that this was the problem, I created the soft link:

```bash
sudo ln -s /lib/x86_64-linux-gnu/libacl.so.1.1.0 /lib/x86_64-linux-gnu/libacl.so
```

Once this was done, I just executed `validate.sh` from each binary folder and I generated the binaries, and they work well with PIN! Just in case you need these binaries, I attach them (they are also available at [BOA](https://github.com/cgr71ii/BOA/tree/master/tests/binaries/LAVA-M)): [LAVA-M_64-bits.tar.gz](https://github.com/vusec/vuzzer64/files/6995666/LAVA-M_64-bits.tar.gz)

Thanks for the help!

**Comment by tosanjay** [comment]
This is great. Thank you @cgr71ii 
And really sorry for responding to this contribution soooo late. I will add these binaries into the repo.
